# prefix will be prepended to all resource names
variable "prefix" {
  type    = string
  default = "sample"
}

# FunctionGraph: Function name
variable "function_name" {
  type    = string
  default = "function_name"
}

# FunctionGraph: Handler name
variable "function_handler_name" {
  type    = string
  default = "function_handler_name"
}

# FunctionGraph: Initializer name
variable "function_initializer_name" {
  type    = string
  default = "function_initializer_name"
}

# name of zip file to deploy, generated by 'dotnet build' command
variable "zip_file_local" {
  type    = string
  default = "path/to/zip_file_name.zip"
}

variable "function_runtime" {
  type    = string
  default = "C#(.NET Core 6.0)"
}

# Resource tag:
variable "tag_app_group" {
  type = string
  default = "csharp-doc-sample-obs-thumbnail"
}
