
# prefix will be prepended to all ressource names
variable "prefix" {
  type    = string
  default = "sample"
}

# FunctionGraph function name
variable "function_name" {
  type    = string
  default = "doc-sample-event-timer"
}

# FunctionGraph handler name
variable "function_handler_name" {
  type    = string
  default = "timer-example"
}

# name of zip file to deploy, generated by 'mvn package' command
variable "zip_file_name" {
  type    = string
  default = "deploy.zip"
}
